module.exports = {

    VUE_APP_API_BASE_URL_DEV: process.env.VUE_APP_API_BASE_URL_DEV,
    DB_VUE_APP_API_BASE_URL_PROHOST:  process.env.VUE_APP_API_BASE_URL_PRO,
    VUE_APP_SOCKET_ENDPOINT:  process.env.VUE_APP_SOCKET_ENDPOINT


}
